// generated by Fast Light User Interface Designer (fluid) version 1.0300

#include "mainWndFl.h"

void MainWindowFl::cb_Close_i(Fl_Return_Button*, void*) {
  hide();
}
void MainWindowFl::cb_Close(Fl_Return_Button* o, void* v) {
  ((MainWindowFl*)(o->parent()->user_data()))->cb_Close_i(o,v);
}

MainWindowFl::MainWindowFl(ITextProcessorD* textProcessor) {
  this->textProcessor = textProcessor;
  { window = new Fl_Double_Window(320, 155);
    window->user_data((void*)(this));
    { dndBox = new DndBox(10, 13, 300, 90, "Drop stuff here");
      dndBox->box(FL_UP_BOX);
      dndBox->color(FL_BACKGROUND_COLOR);
      dndBox->selection_color(FL_BACKGROUND_COLOR);
      dndBox->labeltype(FL_SHADOW_LABEL);
      dndBox->labelfont(3);
      dndBox->labelsize(30);
      dndBox->labelcolor(FL_FOREGROUND_COLOR);
      dndBox->user_data((void*)((IMainWindowFl*)this));
      dndBox->align(Fl_Align(FL_ALIGN_CENTER));
      dndBox->when(FL_WHEN_RELEASE);
    } // DndBox* dndBox
    { Fl_Return_Button* o = new Fl_Return_Button(195, 115, 110, 30, "Close");
      o->callback((Fl_Callback*)cb_Close);
    } // Fl_Return_Button* o
    window->end();
    window->resizable(window);
  } // Fl_Double_Window* window
}

MainWindowFl::~MainWindowFl() {
  puts("~mainWndFl");
  if (window)
    delete window;
  window = 0;
}

void MainWindowFl::show(int argc, char ** argv) {
  window->show(argc, argv);
}

void MainWindowFl::hide() {
  window->hide();
}
